spring.application.name: infra
spring.profiles.active: local

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create-drop 이나 create로 할경우, 자동으로 실행되는 schema & table drop 에서 DDL 오류 발생 (not exist -> not found)
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        show_sql: true
    show-sql: true
    generate-ddl: true

external:
  sopt-makers:
    playground:
      url: https://playground.dev.sopt.org
      token: ${DEV_PLAYGROUND_TOKEN}

logging:
  level:
    sopt.makers.authentication.infra.client.openfeign: DEBUG


---
spring.config.activate.on-profile: dev

spring:
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

external:
  sopt-makers:
    playground:
      url: ${DEV_PLAYGROUND_URL}
      token: ${DEV_PLAYGROUND_TOKEN}


---
spring.config.activate.on-profile: prod
spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: postgresql
external:
  sopt-makers:
    playground:
      url: ${PROD_PLAYGROUND_URL}
      token: ${PROD_PLAYGROUND_TOKEN}

---
spring.config.activate.on-profile: test
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password:
    driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update # create-drop 이나 create로 할경우, 자동으로 실행되는 schema & table drop 에서 DDL 오류 발생 (not exist -> not found)
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          format_sql: true
          globally_quoted_identifiers: true
          show_sql: true
      show-sql: true
      generate-ddl: true

  cloud:
    openfeign:
      lazy-attributes-resolution: true
  #feign:
  #  client:
  #    config:
  #      fake-api:

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql: trace
external:
  sopt-makers:
    playground:
      url: ${DEV_PLAYGROUND_URL}
      token: ${DEV_PLAYGROUND_TOKEN}